var v1 = 10;
var v2 = "HI Mysore";
var v3 = true;
var v4;
var v5 = null;
console.log(v1);
console.log(v2);
console.log(v3);
console.log(v4);
console.log(v5);
console.log("The value of v1 = " + v1 + ", value of v2 = " + v2 + "value of v3 =" + v3);
console.log("the value of v1 = ${v1}, value of v2 = ${v2},value of v3 = ${v3}");
